# Generated by Django 5.2.2 on 2025-08-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_index', '0003_ticketfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tracking_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
